# Default values for dotnet core service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: demochristophertown.azurecr.io/k8s/some-service
  tag: latest
  pullPolicy: Always
  pullSecret: docker-registry

service:
  name: my-service
  type: ClusterIP  #NodePort #Loadbalancer
  externalPort: 5001
  internalPort: 5001
  livenessProbePath: /health
  readinessProbePath: /health

ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - app-service.christophertown.com
  annotations:
      kubernetes.io/ingress.class: nginx-mic
      kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: some-service-tls
      hosts:    
        - app-service.christophertown.com

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

env: {}
  #ConnectionStrings__MongoDB: "mongodb://mongo:27017"
  #Settings__SomeSettingName: "SomeSettingValue"
  #Swagger__OAuthTokenUrl: "https://apiint.newgistics.com/v2/auth/token"
  
envSecrets: {}
#  - name: Settings__DbUserName
#    valueFrom:
#      secretKeyRef:
#        name: dbaccess-secret
#        key: username
#  - name: Settings__DbPassword
#    valueFrom:
#      secretKeyRef:
#        name: dbaccess-secret
#        key: password

horizontalPodAutoscaler:
  enabled: false
  spec:
    minReplicas: 1
    maxReplicas: 1
    metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 70
      type: Resource
