apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "dnc-service.fullname" . }}
  labels:
    app: {{ template "dnc-service.name" . }}
    chart: {{ template "dnc-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "dnc-service.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.service.livenessProbePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: 45
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.service.readinessProbePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: 45
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 10
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: Host
          value: "http://*:{{ .Values.service.internalPort }}"
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end}}
        {{- if .Values.envSecrets }}
{{ toYaml .Values.envSecrets | indent 8 }}
        {{- end -}}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end -}}
      {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 6 }}
      {{- end -}}
